### (1) LU 분해

**LU 분해 (LU decomposition) : 주어진 행렬 A에 대해 하삼각행렬 L과 상삼각행렬 U의 곱으로 인수분해**
- LU 분해는 유일하지 않음
- A를 분해한 후에는 여러 가지 상수벡터 b에 대해 Ax = b를 풀 수 있음
- 제약조건에 따라 일반적으로 이용되는 세 가지 분해법
    - Doolittle 분해법 (Lii = 1, (i = 1, 2, ..., n))
    - Crout 분해법 (Uii = 1, (i = 1, 2, ..., n))
    - Cholesky 분해법 (L = UT)

A를 분해한 후에는 방정식 Ax = b를 풀기가 쉬움
- LUx = b를 Ux = y 기호를 이용하면 Ly = b로 쓸 수 있음. y를 전방대입법으로 구함
- Ux = y에 대해 후방대입법으로 x를 구함
- 해를 구하기 위한 시간이 매우 짧음

### (2) Doolittle 분해법

**분해 단계**

Doolittle 분해법의 두 가지 중요한 특징
- 1. 행렬 U는 Gauss 소거법에서 만들어지는 상삼각행렬과 같음
- 2. L의 비대각 요소는 Gauss 소거법 동안에 이용하는 피봇방정식의 승수 (multiplier)
    - Lij는 Aij를 소거하는 승수

- 소거되는 계수를 치환 (Aij를 Lij로 치환) -> 승수를 계수행렬의 일부인 하삼각 부분에 저장
- L의 대각 요소는 1이므로 저장할 필요가 없음
- 최종적인 형태는 아래와 같다
    - U11 U12 U13
    - L21 U22 U23
    - L31 L32 U33

In [ ]:
for k in range(0, n - 1):
    for i in range(k + 1, n):
        if a[i, k] != 0.0:
            lam = a[i, k] / a[k, k]
            # 각 승수를 A의 하삼각 부분에 저장
            a[i, k + 1:n] = a[i, k + 1:n] - lam * a[k, k + 1:n]
            a[i, k] = lam

**풀이 단계**

In [ ]:
# 전방대입
y[0] = b[0]
for k in range(1, n):
    y[k] = b[k] - dot(a[k, 0:k], y[0:k])

In [2]:
# Doolittle 법에 의한 선형연립방정식 풀이

import numpy as np
from LudDoolittle import *
from PrintMatrix import *

A = np.array([[1.0, 4.0, 1.0],
              [1.0, 6.0, -1.0],
              [2.0, -1.0, 2.0]])
b = np.array([7.0, 13.0, 5.0])

AOrg = A.copy()
bOrg = b.copy()

# [A] 분해
A = decompDoolittle(A)
print("LU 분해: A = ")
print(A)

# LU분해
x = solveDoolittle(A, b)
print("\n계산 결과: x = ", x)
print("\n검토계산: [A]{x} - {b} = ", np.dot(AOrg, x) - bOrg)

LU 분해: A = 
[[ 1.   4.   1. ]
 [ 1.   2.  -2. ]
 [ 2.  -4.5 -9. ]]

계산 결과: x =  [ 5.  1. -2.]

검토계산: [A]{x} - {b} =  [0. 0. 0.]


### (3) Cholesky 분해법

Cholesky 분해법 A = LL^T의 두 가지 제약
- 1. LL^T는 항상 대칭행렬. 따라서 A가 대칭행렬
- 2. 분해 과정에서 A의 요소의 어떤 조합의 제곱근을 포함.
    - 음수의 제곱근을 피하기 위해 A는 반드시 정부호 (positive definite)

- 근사적으로 n^3 / 6회 연산, n회의 제곱근 계산 포함 (LU 분해의 절반)
- 이는 대칭성에 따른 것

- Aij는 Lij에 대한 식에서만 나타남
    - Lij를 한 번 계산하면 Aij는 더 이상 필요하지 않음
    - L을 계산하면 A의 부분에 덮어쓰기를 할 수 있음
- A의 주대각선 윗부분은 건드리지 않음

In [6]:
# Cholesky 법에 의한 선형연립방정식 풀이

import numpy as np
from LudCholesky import *

A = np.array([[4, -2, 2],
              [-2, 2, -4],
              [2, -4, 11]])
b = np.array([4, -2, 3])

AOrg = A.copy()
bOrg = b.copy()

L = decompCholesky(A)
print("LU 분해: L = ")
print(L)

x = solveCholesky(L, b)
print("\n계산 결과: x =", x)
print("\n계산 검토: [A] {x} - {b} = ",np.dot(AOrg, x) - bOrg)

LU 분해: L = 
[[ 2  0  0]
 [-1  2  0]
 [ 1 -4 11]]

계산 결과: x = [1 0 0]

계산 검토: [A] {x} - {b} =  [ 0  0 -1]


### (4) Crout 분해법

- Doolittle 분해법에서 L의 대각 요소는 1
- Crout 분해법에서는 U의 대각 요소가 1

### (5) Gauss-Jordan 소거법

- Gauss 소거법은 피봇방정식 아래에 있는 방정식만을 변환
- Gauss-Jordan 소거법은 피봇방정식 위에 있는 방정식에 대해서도 수행
    - 결과적으로 대각 계수행렬이 만들어짐